### ISSUE TITLE
NKB000000 - add home page

### ISSUE THREAD

**Issue by nealshan2** [nooshhub/rehearsal#1]
Hi @dorachen123 , please add a home.html page and add some content.

**Comment by nealshan2** [comment]
@dorachen123 what's up 💃

**Comment by dorachen123** [comment]
@nealshan2 👍

**Comment by dorachen123** [comment]
@nealshan2 ????#1

**Comment by nealshan2** [comment]
Please add issues that you met while developing.

**Comment by dorachen123** [comment]
1. git clone https://github.com/nooshhub/rehearsal
2. git checkout feature-NKB000000 master
3. git add . 
4. git commit -m "comments" 
5. git push
6. git checkout qa
7. git merge feature-NKB000000 --no-ff
8. git push

Follow git's tips and I did it! 💯

**Comment by nealshan2** [comment]
reopen, please merge your code to scd

**Comment by dorachen123** [comment]
Done

**Comment by nealshan2** [comment]
please merge your code to develop, you may need to send a pull request
