### ISSUE TITLE
NKB000001 - add footer for our site

### ISSUE THREAD

**Issue by nealshan2** [nooshhub/rehearsal#2]
add email address and copyright to it

**Comment by dorachen123** [comment]
well done neal, you dare to merge it without my approve 😠

**Comment by nealshan2** [comment]
reopen for merge code to scd

**Comment by nealshan2** [comment]
merged code to scd

**Comment by nealshan2** [comment]
approved on scd, please merge your code to develop

**Comment by nealshan2** [comment]
merged to develop
